# Generated by Django 3.2.13 on 2022-06-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_management', '0009_humanpost_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('difficulty_name', models.CharField(max_length=30, unique=True, verbose_name='难度层级')),
            ],
            options={
                'verbose_name': '难度',
                'verbose_name_plural': '难度',
                'db_table': 'difficulties',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('subject_name', models.CharField(max_length=30, unique=True, verbose_name='科目名称')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('test_name', models.CharField(max_length=30, unique=True, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(verbose_name='开考时间')),
                ('duration', models.IntegerField(default=150, verbose_name='考试时长')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management.difficulty', verbose_name='难度')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management.subject', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('question_type', models.IntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '填空题'), (3, '判断题'), (4, '解答题')], verbose_name='题目类型')),
                ('knowledge_node', models.CharField(max_length=100, verbose_name='知识点')),
                ('question_main', models.CharField(max_length=300, verbose_name='题干')),
                ('question_answer', models.CharField(max_length=500, verbose_name='参考答案')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management.difficulty', verbose_name='难度')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management.subject', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_management.human', verbose_name='考试')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.test', verbose_name='考试')),
            ],
            options={
                'verbose_name': '监考信息',
                'verbose_name_plural': '监考信息',
                'db_table': 'invigilator',
            },
        ),
    ]
