# Generated by Django 3.2.13 on 2022-06-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0009_humanpost_is_primary'),
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.test', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '试卷题目信息',
                'verbose_name_plural': '试卷题目信息',
                'db_table': 'papers',
            },
        ),
        migrations.AlterField(
            model_name='invigilator',
            name='invigilator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_management.human', verbose_name='监考人'),
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('paper_number', models.IntegerField(unique=True, verbose_name='卷内编号')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.paper', verbose_name='所属试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.question', verbose_name='考题')),
            ],
            options={
                'verbose_name': '试卷题目信息',
                'verbose_name_plural': '试卷题目信息',
                'db_table': 'paper_questions',
            },
        ),
        migrations.CreateModel(
            name='PaperAnswer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('my_answer', models.CharField(max_length=500, verbose_name='题目回答')),
                ('score_get', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_management.human', verbose_name='考生')),
                ('paper_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.paperquestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷题目信息',
                'verbose_name_plural': '试卷题目信息',
                'db_table': 'paper_answers',
            },
        ),
    ]
