# Generated by Django 3.2.13 on 2022-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0010_auto_20220620_0024'),
        ('test_management', '0002_auto_20220605_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': '试卷', 'verbose_name_plural': '试卷'},
        ),
        migrations.AlterModelOptions(
            name='paperanswer',
            options={'verbose_name': '试卷题目回答', 'verbose_name_plural': '试卷题目回答'},
        ),
        migrations.AddField(
            model_name='invigilator',
            name='location',
            field=models.CharField(default='home', max_length=30, verbose_name='监考地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_examinee',
            field=models.ManyToManyField(db_table='test_examinee', null=True, related_name='student_tests', to='human_management.Human', verbose_name='考试考生关联信息'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_organization',
            field=models.ManyToManyField(db_table='test_organization', null=True, related_name='organization_tests', to='human_management.Organization', verbose_name='考试组织关联信息'),
        ),
    ]
