# Generated by Django 3.2.13 on 2022-05-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('organization_type_name', models.CharField(max_length=30, verbose_name='组织类型名称')),
            ],
            options={
                'verbose_name': '组织类型',
                'verbose_name_plural': '组织类型',
                'db_table': 'organization_type',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('permission_name', models.CharField(max_length=30, verbose_name='权限名称')),
                ('organizations', models.ManyToManyField(db_table='organization_permission', related_name='permissions', to='human_management.OrganizationType', verbose_name='组织权限')),
            ],
            options={
                'verbose_name': '权限类型',
                'verbose_name_plural': '权限类型',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('organization_name', models.CharField(max_length=30, verbose_name='组织名称')),
                ('organization_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='down_organization', to='human_management.organizationtype')),
                ('up_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='down_organization', to='human_management.organization')),
            ],
            options={
                'verbose_name': '组织信息',
                'verbose_name_plural': '组织信息',
                'db_table': 'organization',
            },
        ),
    ]
