# Generated by Django 3.2.13 on 2022-05-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='organizations',
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='permissions',
            field=models.ManyToManyField(db_table='organization_permission', related_name='organizations', to='human_management.Permission', verbose_name='组织权限列表'),
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_number',
            field=models.IntegerField(default=0, verbose_name='权限量级'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='down_organization', to='human_management.organizationtype', verbose_name='组织类型'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='up_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='down_organization', to='human_management.organization', verbose_name='上级组织'),
        ),
    ]
