# Generated by Django 3.2.13 on 2022-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0002_auto_20220531_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtype',
            name='permissions',
            field=models.ManyToManyField(db_table='organization_permission', null=True, related_name='organization_types', to='human_management.Permission', verbose_name='组织权限列表'),
        ),
    ]
