# Generated by Django 3.2.13 on 2022-05-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0004_auto_20220531_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('user_id', models.CharField(max_length=18, unique=True, verbose_name='唯一识别编号、账号')),
                ('user_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='human_management.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'db_table': 'human_beings',
            },
        ),
    ]
