# Generated by Django 3.2.13 on 2022-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0005_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='password',
            field=models.CharField(default='abc123456', max_length=128, verbose_name='密码'),
        ),
    ]
