# Generated by Django 3.2.13 on 2022-05-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0006_alter_human_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanPost',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('post_name', models.CharField(max_length=20, unique=True, verbose_name='职位名称')),
            ],
            options={
                'db_table': 'human_post',
            },
        ),
        migrations.AlterField(
            model_name='human',
            name='password',
            field=models.CharField(blank=True, default='abc123456', max_length=128, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='human',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_management.humanpost'),
        ),
    ]
