# Generated by Django 3.2.13 on 2022-05-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0007_auto_20220601_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanpost',
            options={'verbose_name': '职务信息', 'verbose_name_plural': '职务信息'},
        ),
    ]
