# Generated by Django 3.2.13 on 2022-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0008_alter_humanpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanpost',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否主导所在组织'),
        ),
    ]
