# Generated by Django 3.2.13 on 2022-06-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_management', '0009_humanpost_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_management.humanpost', verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='组织名称'),
        ),
    ]
